### ISSUE TITLE
Use HTML5 "download" Attribute

### ISSUE THREAD

**Issue by freedomofkeima** [tkesgar/miyako#2]
Reference:
- http://www.w3schools.com/tags/att_a_download.asp

I'm not sure whether it will work properly or not, but I think it's worth trying :stuck_out_tongue: 

https://github.com/tkesgar/miyako/blob/17c08c3/app/components/image.js#L10

**Comment by tkesgar** [comment]
Added the attribute; works well on Chrome but not on Firefox due to security issues.

Closing this for now.

**Comment by freedomofkeima** [comment]
Okay,

Later on, I'm wondering why Chrome allows this CORS policy while Firefox doesn't. After reading several discussions, it seems the problem is actually located on [their own design](https://bugzilla.mozilla.org/show_bug.cgi?id=923415), which makes their security teams to disallow this `cross-origin` policy. The issue is still opened so we can hope it's being fixed in the future.
