### ISSUE TITLE
Persistent login across tabs and page refreshes

### ISSUE THREAD

**Issue by freedomofkeima** [tkesgar/miyako#4]
It seems the current login session is not referenced properly. It might be better to use [`onAuthStateChanged`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged) for better user's experience. https://auth0.com/blog/firebase-authentication-with-firebase-3.0-and-auth0-integration/ might help.

Not related aside, could you add "https://tkesgar.github.io/miyako/#/" to the repository website description? I often forget where the website URL is :stuck_out_tongue: 

![website](https://cloud.githubusercontent.com/assets/2115470/19012842/88bb523a-87fb-11e6-8a90-2405d63875b8.png)

**Comment by tkesgar** [comment]
I removed the login process and offloaded the API calls to a server backend.

Now there's concerns with API rate limit and security... but it should be working for now.

Also, the repository website is now https://tkesgar-miyako.herokuapp.com/.

**Comment by freedomofkeima** [comment]
:tada: It looks good!

Is there any reason why app level token instead of user level token? :thinking: So, what is the rate limit which is imposed due to this mechanism?

For now, I'll close this PR. Having user level `access token` support in the future might be also good for future enhancement, especially if we want to access some private repositories under specific user.
